version: '3.8'

services:
  backend:
    build:
      context: ./backend/moodii
      dockerfile: ../../docker/backend/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app

  ml:
    build: ./docker/ml
    ports:
      - "8000:8000"
    volumes:
      - ./ml:/app
