services:
  emotion-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moodii-emotion-api
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
    volumes:
      - D:\Moodii\Moodii\ml\CNN+LSTM_Model\logs:/app/logs
      - D:\Moodii\Moodii\ml\CNN+LSTM_Model\model_CLSTM_20_82.h5:/app/model_CLSTM_20_82.h5:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - moodii-network

networks:
  moodii-network:
    driver: bridge
