name: Moodii CI-CD

on:
  push:
    branches: [ main, dev, containerize ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Prepare Maven Wrapper
        run: |
          chmod +x backend/moodii/mvnw
      - name: Build Spring Boot backend
        run: ./backend/moodii/mvnw -B -f backend/moodii/pom.xml clean package -DskipTests
      - name: Upload backend JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: backend/moodii/target/*.jar

  backend-docker:
    needs: build-backend
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      ACR_NAME: ${{ secrets.AZURE_ACR_NAME }}
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Skip backend container build (Azure creds missing or disabled)
        run: echo "Skipping backend Docker/Azure steps."

  ml-docker:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      ACR_NAME: ${{ secrets.AZURE_ACR_NAME }}
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Build & Push ML image (CNN+LSTM)
        uses: azure/cli@v2
        with:
          inlineScript: |
            az acr login --name $ACR_NAME
            docker build -t $ACR_NAME.azurecr.io/moodii-ml-cnnlstm:$IMAGE_TAG -f ml/CNN+LSTM_Model/Dockerfile ml/CNN+LSTM_Model
            docker push $ACR_NAME.azurecr.io/moodii-ml-cnnlstm:$IMAGE_TAG

  android-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17 (Android Gradle requirement)
        uses: actions/setup-java@v4
        with:
            distribution: temurin
            java-version: '17'
            cache: gradle
      - name: Grant execute permission
        run: chmod +x ./frontend/gradlew
      - name: Build Release APK (Unsigned)
        working-directory: frontend
        run: ./gradlew :app:assembleProdRelease --stacktrace
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: moodii-prod-release-apk
          path: frontend/app/build/outputs/apk/prod/release/*.apk

  deploy-aci:
    needs: [backend-docker, ml-docker]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      ACR_NAME: ${{ secrets.AZURE_ACR_NAME }}
      RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
      LOCATION: ${{ secrets.AZURE_LOCATION }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
      ML_IMAGE_TAG: ${{ github.sha }}
      BACKEND_IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Skip Azure deployment (credentials not configured)
        run: echo "Skipping Azure Container Instance deployment."
