name: Android CI

on:
  push:
    paths:
      - "frontend/**"
    branches: [main, dev]
  pull_request:
    paths:
      - "frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build Android App
        run: ./gradlew assembleDebug --stacktrace
