name: ML Model CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ml/CNN+LSTM_Model/requirements.txt

    # Step 4: Run tests (lightweight)
    - name: Run tests
      run: |
        if [ -d ml/CNN+LSTM_Model/tests ]; then pytest -q ml/CNN+LSTM_Model/tests; else echo "No tests directory"; fi

    # Step 5: Build Docker image
    - name: Build Docker image
      run: docker build -f ml/CNN+LSTM_Model/Dockerfile -t moodii-ml:${{ github.sha }} .

    # Step 6: Push Docker image to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: docker push moodii-ml:${{ github.sha }}

    # Step 7: Deploy to server (optional)
    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
        docker pull moodii-ml:${{ github.sha }}
        docker stop moodii-ml || true
        docker rm moodii-ml || true
        docker run -d --name moodii-ml -p 5000:5000 moodii-ml:${{ github.sha }}
        EOF